version: "3"
services:
  web:
    container_name: web
    build:
      context: .
      dockerfile: Dockerfile
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - 8000:80
      - 443:443
    volumes:
      - .:/var/www/html
